### PR TITLE
Speedup, refactoring and modernization

### PR DESCRIPTION
**Pull request by fjwillemsen**
Hi all! A while ago I implemented `python-constraint` in [Kernel Tuner](https://github.com/KernelTuner/kernel_tuner), an auto-tuning framework where we need to obtain all solutions on user-specified parameters and constraints before starting optimization. `python-constraint` works great, but it had some room for improvement, especially performance-wise. 
I thus decided to fork `python-constraint` and make some changes, the following:
- Cythonized the package
- Added the `OptimizedBacktracking` solver based on [issue #62](https://github.com/python-constraint/python-constraint/issues/62)
- Added type-hints to improve Cythonization
- Added the MaxProd and MinProd constraints
- Improved pre-processing for the MaxSum constraint
- Optimized the Function constraint
- Added `getSolutionsOrderedList` and `getSolutionsAsListDict` functions for efficient result shaping
- Overall optimization of common bottlenecks
- Split the codebase into multiple files for convenience
- Switched from `setup.py` to `pyproject.toml`
- Achieved and requires test coverage of at least 65%
- Added `nox` for local testing against all supported Python versions 
- Added `ruff` for codestyle testing
- Dropped Python 3.4, 3.5, 3.6, 3.7 support

In all, this results in a huge speedup of >150x on a benchmark of 112 synthetic searchspaces: 
image

I'd like to hear what the mainainers think about these changes and would be happy to see them integrated! Before releasing this, I think it would be a good idea to revise the package publishing process, and consider switching to GitHub Actions (I can help with this). If there are any questions, please let me know!

### CODE REVIEW

**Comment by scls19fr** [comment]
Hi @fjwillemsen 

Very pleased to see such a contribution. I'm no longuer maintaining this repository. I sent you and invite to be member of https://github.com/python-constraint/ GH org and also grant you write access to https://github.com/python-constraint/python-constraint/ 
Feel free to take the lead on the project and improve it.
If you need something more just let me know.

Kind regards

Sébastien

**Comment by fjwillemsen** [comment]
@scls19fr thank you very much, I'll do my best :)
Perhaps it is not practical, but given that you will no longer maintain, could you make me owner instead of member? It appears I currently do not have access to the repository secrets, which prohibits a release on PyPI

**Comment by scls19fr** [comment]
Done.

**Comment by scls19fr** [comment]
https://pypi.org/project/python-constraint/ belongs to @niemeyer so I can't give you access.
You can either ask him or create a new PyPi project python-constraint2 or 3 for example.

**Comment by fjwillemsen** [comment]
Thank you! I have contacted @niemeyer via email, for continuity it would be ideal to keep it on the same package, I hope this will be possible. 
Thank you very much for all of your contributions to python-constraint throughout the years!

**Comment by scls19fr** [comment]
Great work! Thanks @fjwillemsen 
Renaming master branch to main should also be considered
https://github.com/github/renaming

**Comment by fjwillemsen** [comment]
Good suggestion! Renamed master branch to main

**Comment by fjwillemsen** [comment]
My emails to @niemeyer regarding PyPI access seem to go unanswered. @scls19fr could you perhaps get in touch with @niemeyer, or provide me with an alternative means of contact? My contact details are on [my website](https://fjwillemsen.com/).

**Comment by fjwillemsen** [comment]
My emails to @niemeyer regarding PyPI access seem to go unanswered. @scls19fr could you perhaps get in touch with @niemeyer, or provide me with an alternative means of contact? My contact details are on [my website](https://fjwillemsen.com/).

**Comment by scls19fr** [comment]
what about a new name?
python-constraint2 or 3 or something else.
So we could be totally free.
I think it will be the simplest solution.

**Comment by fjwillemsen** [comment]
Yes, definitely, I had already created a [python-constaint2](https://pypi.org/project/python-constraint2/) for beta testing. However, `python-constraint` had 148,000 downloads in the past month, which is a very solid user base I would prefer not to abandon if we have a choice.

**Pull request merged**
